version: 1
manifests:
  environments: []
  knowledge_bases:
  - deploy/wxo/knowledge-bases/pokemon-tcg-kb.yaml
  agents:
  - deploy/wxo/agents/pokemon-tcg-agent.yaml
  channels: []
  tools:
  - deploy/wxo/tools/pokemon_tcg_stats_tools.py
